FROM nvcr.io/nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04

WORKDIR /workspace/

ENV PYTHONPATH /workspace/

RUN apt-get update && apt-get install python3 python3-pip -y
RUN ln -s /bin/python3 /bin/python
RUN pip install --no-cache-dir -U torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
RUN pip install --no-cache-dir -U xformers --index-url https://download.pytorch.org/whl/cu121
RUN pip install --no-cache-dir -U bitsandbytes

COPY . /workspace

RUN pip install --no-cache-dir -r /workspace/requirements.txt
